### ISSUE TITLE
Rinominare branch mergiati

### ISSUE THREAD

**Issue by RiccardoAgatea** [GruppOne/stalker-mobile-app#25]
Bisogna prependere `stale/` al nome del branch.

[Qui](https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/) istruzioni su come fare con git. In alternativa, @erclu dice che usando gitgraph su vscode basta cambiare il nome del branch remoto.

**Comment by erclu** [comment]
sistemato quando ho cambiato retroattivamente il modo in cui mergiamo le pr
