### ISSUE TITLE
Valutare se conviene sviluppare e testare l'app in una VM

### ISSUE THREAD

**Issue by erclu** [GruppOne/stalker-mobile-app#6]
So che almeno un paio di noi non hanno cellulari nuovissimi quindi forse questo semplificherebbe le cose. Inoltre è desiderabile standardizzare l'ambiente di sviluppo per eliminare bug e rallentamenti dovuti al fatto che usiamo device diverse

**Comment by RiccardoCestaro** [comment]
A parer mio testare l'applicazione su più ambienti Android 5.0+ diversi ha un vantaggio superiore che testarla solo nello stesso ambiente.
Quindi resterei all'idea di testare e sviluppare l'applicazione in diversi ambienti, non penso ci siano grossi problemi tra device diversi.
