### ISSUE TITLE
Implementare l'edit text per la data di nascita nella SignUpActivity

### ISSUE THREAD

**Issue by fabioscettro** [GruppOne/stalker-mobile-app#60]
1. Usiamo un `inputType="date"` e poi implementiamo la validazione e la coversione a `date`

2. Usiamo il _MaterialDatePicker_ https://developer.android.com/reference/com/google/android/material/datepicker/MaterialDatePicker

**Comment by TobiaApolloni** [comment]
Io sarei per il material date picker, cosa dici? Se una cosa già esiste, inutile rifarla

**Comment by erclu** [comment]
anche io userei quello di android. In teoria dovrebbe anche funzionare meglio con telefoni vecchi perché credo che ciascuna versione di android abbia il suo datepicker diverso che però conforma a quell'interfaccia/classe

**Comment by fabioscettro** [comment]
Sì sono d'accordo
