### ISSUE TITLE
Scroll nella pagina dell'organizzazione

### ISSUE THREAD

**Issue by RiccardoAgatea** [GruppOne/stalker-mobile-app#86]
Se il cellulare è in orizzontale, la pagina viene tagliata (ovviamente), ma lo scroll fa conflitto con le gesture della mappa. Ad esempio, se si muovono due dita in verticale scrolla la pagina invece di muovere la mappa.

**Comment by fabioscettro** [comment]
Io direi di bloccare la possibilità della rotazione
