### ISSUE TITLE
Dettagli

### ISSUE THREAD

**Issue by RiccardoAgatea** [GruppOne/stalker-mobile-app#96]
- [x] Gif di caricamento per login/signup + connessione a organizzazione
- [ ] Messaggi di errore al ritorno dalle richieste http
- [x] Far partire la main page quando arriva il jwt, invece di aspettare anche le info utente
- [ ] Logout
- [ ] Warning all'uscita dalla main page (dialog tipo "Are you sure you want to go away?", se premi "yes" fa automaticamente anche il logout)

**Comment by RiccardoAgatea** [comment]
- [ ] rifattorizzare il recupero delle organizzazioni (get /organizations ritorna gli id dei place, che vanno poi presi uno per uno al bisogno)

**Comment by RiccardoAgatea** [comment]
- [ ] Barra di ricerca (?)

**Comment by RiccardoAgatea** [comment]
- [ ] L'icona dell'app ha un bordino bianco

**Comment by RiccardoAgatea** [comment]
- [ ] Colori dei place presi dal db invece che generati casualmente

**Comment by RiccardoAgatea** [comment]
- [ ] #60

**Comment by RiccardoAgatea** [comment]
- [ ] #86

**Comment by RiccardoAgatea** [comment]
- [ ] Aggiungere i place ai poligoni sulla mappa in modo che quando l'utente clicca sul poligono esca un popup con le informazioni sul place.
  - Aggiungere il place si può fare con il tag del poligono, ma poi non so se il poligono è effettivamente cliccabile, e se lo è come far apparire il popup
  - Se non è cliccabile, bisogna aggiungere le info del place da qualche parte, es sotto la mappa

**Comment by fabioscettro** [comment]
- [ ] quando si cambia fragment tramite la bottom bar bisogna cambiare la scritta nella top bar: "Stalker" è solo un placeholder che va bene per le view di login e sign up, ma quando si vede la lista delle organizzazioni deve esserci scritto "organizations list" o "List", quando si seleziona connected deve apparire "Connected" e così via

**Comment by fabioscettro** [comment]
- [ ] mettere apposto il colore delle icone nella bottom bar

**Comment by fabioscettro** [comment]
- [ ] lo sfondo dei fragment di _Organizations_ e _Connected_ deve essere #FFFFFF (bianco), e non #DFDFDF (grigio chiaro) come sono al momento. Invece nel fragment _Report_ va benissimo #DFDFDF perché ci darà il contrasto con le mat card che andremo a mettere per visualizzare la dashboard
